# ---- Simple depends ----
[hello.service]
isolate = "none"
type = "forking"  # Should be one-shot
depends = ["foo.bar.service"]
cmd = ["/bin/diary", "/bin/sh", "-c", "echo hello world"]

[foo.bar.service]
isolate = "none"
type = "forking"  # Should be one-shot
cmd = ["/bin/diary", "/bin/sh", "-c", "echo i am foo bar"]
# ------------------------


# ---- Forking depends (waits until up) ----
[sleepy.service]
isolate = "none"
type = "forking"
cmd = ["/bin/sleep", "2"]

[wakey.service]
isolate = "none"
type = "forking"  # Should be one-shot
cmd = ["/bin/diary", "/bin/sh", "-c", "echo sleep finished"]
depends = ["sleepy.service"]
# ------------------------------------------


# ---- Essential services ----
[shell.service]
isolate = "none"
tty = "/dev/tty1"
cmd = ["/bin/sh"]
# ----------------------------


# ---- Targets ----
[interactive.target]
depends = [
    "shell.service",
    "hello.service",
    "wakey.service",
]
# -----------------